// Help Menu Category Definitions
// roleLevel: 0 = everyone, 1 = support/mod, 2 = admin only

const CATEGORIES = [
  {
    id: 'ai_support',
    label: '🤖 AI Support',
    description: 'Ask the AI assistant anything',
    roleLevel: 0,
    commands: [
      { name: '/ask or !ask', description: 'Ask the AI a question about FundedCobra rules and policies', example: '!ask What are the daily loss limits?' },
    ],
  },
  {
    id: 'rules',
    label: '📜 Rules & Knowledge Base',
    description: 'View rules and manage the knowledge base',
    roleLevel: 0,
    adminCommands: [
      { name: '!import-url <url>', description: 'Import rules from a URL into the knowledge base' },
      { name: '!import-text', description: 'Import raw text into the knowledge base' },
      { name: '!sync-website', description: 'Sync the FundedCobra website into the knowledge base' },
      { name: '!sources', description: 'List all knowledge base sources' },
      { name: '!delete-source <id>', description: 'Delete a knowledge base source' },
    ],
    commands: [
      { name: '/rules or !rules', description: 'View the server rules', example: '!rules' },
    ],
  },
  {
    id: 'leads',
    label: '💼 Leads & Sales',
    description: 'Lead tracking and CRM tools',
    roleLevel: 1,
    commands: [
      { name: '!leads [status]', description: 'List all leads', example: '!leads new' },
      { name: '!lead <@user>', description: 'View a lead profile', example: '!lead @user' },
      { name: '!lead-search <query>', description: 'Search for a lead', example: '!lead-search John' },
      { name: '!lead-status <@user> <status>', description: 'Update lead status (new/warm/hot/converted/lost)' },
      { name: '!lead-note <@user> <note>', description: 'Add a note to a lead' },
      { name: '!export-leads', description: 'Export all leads as CSV' },
    ],
  },
  {
    id: 'tickets',
    label: '🎫 Tickets',
    description: 'Support ticket management',
    roleLevel: 0,
    adminCommands: [
      { name: '/ticket-panel or !ticket-panel', description: 'Send the interactive ticket creation panel' },
      { name: '/claim or !claim', description: 'Claim a ticket and pause AI assistance' },
      { name: '/unclaim or !unclaim', description: 'Unclaim a ticket and optionally re-enable AI' },
      { name: '/ticket-ai-on or !ticket-ai-on', description: 'Manually enable AI in the current ticket' },
      { name: '/ticket-ai-off or !ticket-ai-off', description: 'Manually disable AI in the current ticket' },
      { name: '/add-user or !add-user <@user>', description: 'Add a user to the current ticket' },
      { name: '/remove-user or !remove-user <@user>', description: 'Remove a user from the current ticket' },
      { name: '/ticket-status or !ticket-status', description: 'View current ticket status and metadata' },
      { name: '/ticket-transcript or !ticket-transcript', description: 'Generate or look up a ticket transcript' },
      { name: '!ai-suggest <question>', description: 'Ask the AI for a suggested staff response' },
      { name: '/set-ticket-category', description: 'Set the default ticket category channel' },
      { name: '/set-ticket-log', description: 'Set the ticket events log channel' },
      { name: '/set-ticket-transcript-channel', description: 'Set the ticket transcript channel' },
      { name: '/set-support-role', description: 'Set the support role for tickets' },
      { name: '/set-ticket-ai-mode', description: 'Set default AI mode for new tickets' },
    ],
    commands: [
      { name: '/ticket or !ticket [category]', description: 'Open a support ticket', example: '!ticket Payout Issue' },
      { name: '/tickets or !tickets', description: 'List your open tickets' },
      { name: '/closeticket or !close', description: 'Close an open ticket' },
    ],
  },
  {
    id: 'moderation',
    label: '🛡️ Moderation',
    description: 'Server moderation tools',
    roleLevel: 1,
    commands: [
      { name: '!warn <@user> <reason>', description: 'Issue a warning to a user' },
      { name: '!warnings <@user>', description: 'View a user\'s warnings' },
      { name: '!clearwarns <@user>', description: 'Clear all warnings for a user' },
      { name: '!mute <@user> <duration> [reason]', description: 'Timeout a user (e.g. 10m, 1h, 1d)' },
      { name: '!unmute <@user>', description: 'Remove a timeout from a user' },
      { name: '!kick <@user> [reason]', description: 'Kick a user from the server' },
      { name: '!ban <@user> [duration] [reason]', description: 'Ban a user (optionally temporarily)' },
      { name: '!unban <userId> [reason]', description: 'Unban a user by ID' },
      { name: '!softban <@user> [reason]', description: 'Ban and immediately unban to clear messages' },
      { name: '!purge <amount>', description: 'Delete up to 100 messages' },
      { name: '!lock [reason]', description: 'Lock the current channel' },
      { name: '!unlock [reason]', description: 'Unlock the current channel' },
      { name: '!slowmode <seconds>', description: 'Set channel slowmode (0 to disable)' },
      { name: '!modlogs <@user>', description: 'View a user\'s moderation history' },
      { name: '!case <caseId>', description: 'Look up a moderation case' },
      { name: '!deletecase <caseId> [reason]', description: 'Void a moderation case' },
      { name: '!watch <@user> <reason>', description: 'Add user to watchlist' },
      { name: '!unwatch <@user>', description: 'Remove user from watchlist' },
      { name: '!blacklist <@user> <reason>', description: 'Blacklist a user' },
      { name: '!unblacklist <@user>', description: 'Remove user from blacklist' },
    ],
  },
  {
    id: 'welcome',
    label: '👋 Welcome System',
    description: 'Configure the welcome system',
    roleLevel: 2,
    commands: [
      { name: '!set-welcome-channel #channel', description: 'Set the welcome channel' },
      { name: '!set-welcome-message <msg>', description: 'Set the welcome message' },
      { name: '!set-welcome-banner <url>', description: 'Set the welcome banner image' },
      { name: '!set-welcome-role @role', description: 'Set the auto-assign role' },
      { name: '!set-welcome-dm <msg>', description: 'Set the welcome DM message' },
      { name: '!set-welcome-button <label> <url>', description: 'Add a button to the welcome message' },
    ],
  },
  {
    id: 'announcements',
    label: '📢 Announcements',
    description: 'Create and schedule announcements',
    roleLevel: 2,
    commands: [
      { name: '!announcement-create', description: 'Create a new announcement' },
      { name: '!announcement-send <id>', description: 'Send an announcement immediately' },
      { name: '!announcement-schedule <id> <time>', description: 'Schedule an announcement' },
      { name: '!announcement-list', description: 'List all announcements' },
    ],
  },
  {
    id: 'giveaways',
    label: '🎁 Giveaways',
    description: 'Run and manage giveaways',
    roleLevel: 2,
    commands: [
      { name: '!giveaway-create "<prize>" <duration> [winners]', description: 'Create a giveaway' },
      { name: '!giveaway-start <id> [#channel]', description: 'Start a pending giveaway' },
      { name: '!giveaway-end <id>', description: 'End a giveaway early' },
      { name: '!giveaway-reroll <id>', description: 'Reroll a winner' },
      { name: '!giveaway-list', description: 'List all giveaways' },
      { name: '!giveaway-cancel <id>', description: 'Cancel a giveaway' },
    ],
  },
  {
    id: 'social',
    label: '📱 Social Notifier',
    description: 'Auto-post social media updates',
    roleLevel: 2,
    commands: [
      { name: '!social-add <platform> <handle/url>', description: 'Add a social account to monitor (youtube/instagram/x/tiktok)' },
      { name: '!social-remove <id>', description: 'Remove a monitored account' },
      { name: '!social-list', description: 'List all monitored social accounts' },
      { name: '!social-channel #channel', description: 'Set notification channel' },
      { name: '!social-ping @role/everyone/here/none', description: 'Set ping for notifications' },
      { name: '!social-message <platform> <template>', description: 'Customize notification message' },
      { name: '!social-test <id>', description: 'Send a test notification' },
      { name: '!social-check-now', description: 'Manually trigger a check for new posts' },
      { name: '!social-logs', description: 'View recent notification logs' },
      { name: '!social-reactions <platform> <e1> [e2] [e3]', description: 'Set auto-reactions for platform notifications' },
    ],
  },
  {
    id: 'booster',
    label: '🚀 Booster Appreciation',
    description: 'Auto-thank server boosters with premium embeds',
    roleLevel: 2,
    commands: [
      { name: '!booster-enable / !booster-disable', description: 'Enable or disable the booster appreciation system' },
      { name: '!set-booster-channel #channel', description: 'Set the channel where booster messages are posted' },
      { name: '!set-booster-message <msg>', description: 'Set the booster message (supports {user} {server} {boostCount} {boostTier} {brand})' },
      { name: '!set-booster-banner <url>', description: 'Set the banner image shown in booster embeds' },
      { name: '!set-booster-thumbnail <url>', description: 'Set the thumbnail/GIF shown in booster embeds' },
      { name: '!set-booster-role @role', description: 'Set a reward role automatically given to boosters' },
      { name: '!remove-booster-role', description: 'Remove the configured booster reward role' },
      { name: '!set-booster-reactions <e1> <e2> ...', description: 'Set auto-reactions added to booster messages' },
      { name: '!booster-dm-enable / !booster-dm-disable', description: 'Enable or disable DM thank-you messages to boosters' },
      { name: '!set-booster-dm <msg>', description: 'Set the DM thank-you message sent to boosters' },
      { name: '!booster-preview', description: 'Preview the booster message using yourself as sample' },
      { name: '!booster-stats', description: 'View server boost stats and booster system status' },
      { name: '!booster-list', description: 'List all current server boosters' },
      { name: '!booster-logs', description: 'View recent boost event logs' },
    ],
  },
  {
    id: 'autorole',
    label: '🎭 Auto Role',
    description: 'Automatically assign a role to new members on join',
    roleLevel: 2,
    commands: [
      { name: '!autorole-enable / !autorole-disable', description: 'Enable or disable the auto role system' },
      { name: '!set-autorole @role', description: 'Set the role automatically given to new members' },
      { name: '!remove-autorole', description: 'Remove the configured auto role' },
      { name: '!set-autorole-delay <seconds>', description: 'Set a delay before the role is assigned (0 = instant)' },
      { name: '!set-autorole-log #channel', description: 'Set the channel where role assignment logs are sent' },
      { name: '!autorole-ignore-bots-enable / !autorole-ignore-bots-disable', description: 'Control whether bots receive the auto role' },
      { name: '!autorole-status', description: 'View auto role configuration and stats' },
      { name: '!autorole-preview', description: 'Preview what happens when a new member joins' },
      { name: '!autorole-logs', description: 'View recent role assignment logs' },
    ],
  },
  {
    id: 'admin',
    label: '⚙️ Admin Settings',
    description: 'Bot configuration and administration',
    roleLevel: 2,
    commands: [
      { name: '!set-prefix <prefix>', description: 'Change the bot command prefix' },
      { name: '!set-modlog #channel', description: 'Set the moderation log channel' },
      { name: '!set-help-banner <url>', description: 'Set the help menu banner image' },
      { name: '!set-help-thumbnail <url>', description: 'Set the help menu thumbnail' },
      { name: '!stats', description: 'View bot and server statistics' },
      { name: '!dashboard', description: 'View the admin dashboard' },
      { name: '!reload <command>', description: 'Reload a command without restarting' },
    ],
  },
  {
    id: 'utility',
    label: '🔧 Utility',
    description: 'General utility commands',
    roleLevel: 0,
    commands: [
      { name: '/ping or !ping', description: 'Check bot latency and status' },
      { name: '/help or !help', description: 'Show this help menu' },
      { name: '/pricing or !pricing', description: 'View FundedCobra pricing' },
      { name: '/accounts or !accounts', description: 'View account types and sizes' },
      { name: '/payouts or !payouts', description: 'View payout information' },
      { name: '/offer or !offer', description: 'View current offers and deals' },
    ],
  },
];

module.exports = { CATEGORIES };
